# Generated by Django 4.1.6 on 2023-02-12 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('other', 'Other'), ('study', 'Study'), ('finance', 'Finance'), ('work', 'Work'), ('sport', 'Sport'), ('social', 'Social'), ('home', 'Home')], max_length=10),
        ),
        migrations.AlterField(
            model_name='event',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10),
        ),
        migrations.AlterField(
            model_name='event',
            name='repeat',
            field=models.CharField(choices=[('none', 'No repeat'), ('daily', 'Everyday'), ('weekly', 'Once a Week'), ('monthly', 'Once a Month'), ('yearly', 'Once a Year')], max_length=10),
        ),
    ]
