# Generated by Django 4.1.6 on 2023-07-23 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_category_alter_event_priority_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['start_time', 'priority']},
        ),
    ]
