# Generated by Django 4.1.6 on 2023-02-12 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habit',
            options={'ordering': ['time', 'priority']},
        ),
    ]
