# Generated by Django 4.1.6 on 2023-02-17 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_alter_habit_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habit',
            old_name='habit',
            new_name='title',
        ),
    ]
