# Generated by Django 4.1.6 on 2023-02-17 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_rename_habit_habit_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='time',
            field=models.TimeField(blank=True),
        ),
    ]
