# Generated by Django 4.1.6 on 2023-07-16 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_alter_habit_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habit',
            options={'ordering': ['priority']},
        ),
        migrations.RemoveField(
            model_name='habit',
            name='time',
        ),
    ]
